version: 1
workflows:
  experiment-workflow:
    steps:
        name: "param-file-experiment"
        command: experiment.run_single_node
        params:
          command: pip install -r ml-agents/setup.py && mlagents-learn config/trainer_config.yaml --train --run-id=3DBall01
          container: tensorflow/tensorflow:1.13.1-gpu-py3
          experimentEnv:
            EPOCHS_EVAL: 5
            EVAL_SECS: 10
            MAX_STEPS: 1000
            TRAIN_EPOCHS: 10
          machineType: P4000
          modelPath: /model
          modelType: Tensorflow
          name: mnist-cli-config-yaml
triggers: 
      branches:
      only: master